# Generated by Django 2.2.3 on 2019-08-01 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awsreviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Search',
        ),
    ]
